/**
 * update-core/build.mjs — 更新核心的编译脚本（538 落点决议的字面落实）
 *
 * 只转译不打包：用仓库现成的 esbuild 把 update-core/src/ 下每个 TS 文件
 * 一对一转成 src/shared/update/ 下的同名 JS；另跑 tsc --noEmit 只做类型检查。
 * 生成的 JS 提交到 git；改了 TS 没重新生成，新鲜度门禁变红。
 *
 * 用法：node update-core/build.mjs（在仓库根目录）
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'
import { createRequire } from 'node:module'
import * as esbuild from 'esbuild'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SRC_DIR = resolve(ROOT, 'update-core/src')
const OUT_DIR = resolve(ROOT, 'src/shared/update')

const UNITS = [
  { ts: 'ports.ts', js: 'ports.js' },
  { ts: 'service.ts', js: 'service.js' },
  { ts: 'commands.ts', js: 'commands.js' },
]

function headerFor(tsName) {
  return `// AUTO-GENERATED by node update-core/build.mjs — DO NOT EDIT. Source: update-core/src/${tsName}\n`
}

/** 与新鲜度门禁同一口径：转译加包头，换行归一，末尾恰好一个换行。 */
export function transpileUnit(tsName) {
  const tsPath = resolve(SRC_DIR, tsName)
  const source = readFileSync(tsPath, 'utf8')
  const out = esbuild.transformSync(source, {
    loader: 'ts',
    format: 'esm',
    // 保守目标：Node 宿主与浏览器闭包两边都跑得动。
    target: 'es2020',
  })
  const body = out.code.replace(/\r\n/g, '\n').replace(/\s+$/, '') + '\n'
  return headerFor(tsName) + body
}

function runTypeCheck() {
  const require = createRequire(resolve(ROOT, 'package.json'))
  let tscBin
  try {
    tscBin = resolve(dirname(require.resolve('typescript/package.json')), 'bin/tsc')
  } catch {
    throw new Error('[update-core] 找不到 typescript：请先运行 pnpm install（devDependencies 含 typescript）')
  }
  const r = spawnSync(process.execPath, [tscBin, '-p', resolve(ROOT, 'update-core/tsconfig.json')], {
    encoding: 'utf8',
  })
  if (r.status !== 0) {
    throw new Error(`[update-core] tsc --noEmit 未通过：\n${r.stdout || ''}${r.stderr || ''}`)
  }
  console.log('[update-core] tsc --noEmit 通过')
}

function main() {
  runTypeCheck()
  mkdirSync(OUT_DIR, { recursive: true })
  for (const u of UNITS) {
    const text = transpileUnit(u.ts)
    const outPath = resolve(OUT_DIR, u.js)
    writeFileSync(outPath, text, 'utf8')
    console.log(`[update-core] ${u.ts} -> src/shared/update/${u.js}（${text.split('\n').length} 行）`)
  }
}

const invoked = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (invoked) {
  try {
    main()
  } catch (e) {
    console.error((e && e.message) || e)
    process.exit(1)
  }
}
