// AUTO-GENERATED by node refresh-core/build.mjs — DO NOT EDIT. Source: refresh-core/src/failure-window.ts
export function failureWindowOf(state) {
  const s = state || {};
  const failures = typeof s.failuresSinceSuccess === "number" && isFinite(s.failuresSinceSuccess) && s.failuresSinceSuccess > 0 ? Math.floor(s.failuresSinceSuccess) : 0;
  const started = typeof s.backoffWindowStartedAt === "number" && isFinite(s.backoffWindowStartedAt) && s.backoffWindowStartedAt > 0 ? s.backoffWindowStartedAt : 0;
  return { failures, windowStartedAt: started };
}
export function windowLengthMs(failures, backoffMs, extraMs) {
  const n = typeof failures === "number" && isFinite(failures) && failures > 0 ? Math.floor(failures) : 0;
  const base = typeof backoffMs === "number" && isFinite(backoffMs) && backoffMs > 0 ? backoffMs : 0;
  const extra = typeof extraMs === "number" && isFinite(extraMs) && extraMs > 0 ? extraMs : 0;
  if (n <= 0) return 0;
  return base + extra;
}
export function halfOpenTrialIsDue(state, now, backoffMs, extraMs) {
  if (typeof now !== "number" || !isFinite(now)) return false;
  if (!(state.windowStartedAt > 0)) return false;
  return now - state.windowStartedAt >= windowLengthMs(state.failures, backoffMs, extraMs);
}
export function consumeHalfOpenTrial(now) {
  return typeof now === "number" && isFinite(now) && now > 0 ? now : 0;
}
export function recordFailure(state, now) {
  const failures = (state.failures > 0 ? Math.floor(state.failures) : 0) + 1;
  return { failures, windowStartedAt: consumeHalfOpenTrial(now) };
}
