// AUTO-GENERATED by node scripts/build.mjs (px-ts) — DO NOT EDIT. Source: views/primitives/PxBtn.ts
const PxBtn = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const cls = "px-btn" + (p.hot ? " hot" : "") + (p.mini ? " mini" : "") + (p.loading ? " loading" : "");
  return h("button", {
    type: "button",
    className: cls,
    disabled: p.disabled || p.loading || void 0,
    title: p.title || void 0,
    onClick: p.loading ? void 0 : p.onClick
  }, [
    h("span", { key: "spin", className: "px-spin", "aria-hidden": true }),
    h("span", { key: "label" }, p.children)
  ]);
};
export {
  PxBtn
};
