// AUTO-GENERATED by node scripts/build.mjs (px-ts) — DO NOT EDIT. Source: views/primitives/PxDot.ts
const PxDot = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const bg = p.color || (p.level === "warn" ? "#f59e0b" : p.level === "bad" ? "#a3231a" : p.level === "ok" ? "#0e8a16" : "var(--dc,#0e8a16)");
  return h("span", { className: "px-dot", style: { background: bg }, "aria-hidden": true });
};
export {
  PxDot
};
