// AUTO-GENERATED by node scripts/build.mjs (px-ts) — DO NOT EDIT. Source: views/primitives/PxNum.ts
const PxNum = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const n = Number(p.n) || 0;
  return h("span", { className: "px-num", "aria-hidden": true }, n < 10 ? "0" + n : String(n));
};
export {
  PxNum
};
