// AUTO-GENERATED by node scripts/build.mjs (px-ts) — DO NOT EDIT. Source: views/primitives/PxSeal.ts
const PxSeal = function() {
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  return h("span", { className: "px-seal", "aria-hidden": true });
};
export {
  PxSeal
};
