// AUTO-GENERATED by node scripts/build.mjs (px-ts) — DO NOT EDIT. Source: views/primitives/PxStatusLine.ts
const PxStatusLine = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  return h("div", { className: "px-statusline" }, [
    h(PxStateIcon, { key: "ic", kind: p.icon }),
    h("span", { key: "tx" }, p.text)
  ]);
};
export {
  PxStatusLine
};
