// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/SkillsTab.ts
export const SkillsTab = ({ st }) => {
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const groups = compute(st);
  let rec = [];
  let recTitle = tr("skill.generic");
  const recMapNum = (function() {
    try {
      if (st && Array.isArray(st.navStack)) {
        for (let i = st.navStack.length - 1; i >= 0; i--) {
          const e = st.navStack[i];
          if (e && e.kind === "map" && typeof e.n === "number" && !isNaN(e.n)) return e.n;
        }
        return null;
      }
    } catch (e) {
    }
    if (st && st.activeMap !== null && st.activeMap !== void 0) {
      const v = Number(st.activeMap);
      if (!isNaN(v)) return v;
    }
    return null;
  })();
  if (recMapNum !== null) {
    const g = findGroupByIdentity(groups, recMapNum, st.activeEffortId || "");
    if (g && /research/.test(g.m.notes)) rec = ["research"];
    if (g && /grill/.test(g.m.notes)) rec = ["grilling", "domain-modeling"];
    if (g) recTitle = tr("skill.notes", { m: g.m.title });
  }
  if (!rec.length) rec = ["ask-matt"];
  const items = SKILLS.map(function(sk) {
    return {
      name: sk.name,
      level: sk.level,
      use: tr("skilldesc." + sk.name),
      recommended: rec.indexOf(sk.name) >= 0
    };
  });
  const itemOf = function(name) {
    for (let i = 0; i < items.length; i++) if (items[i].name === name) return items[i];
    return null;
  };
  const d = st && st.pixelDetail ? st.pixelDetail : null;
  const loadingName = d && d.phase === "loading" ? d.name : null;
  const head = h("div", { style: { display: "flex", alignItems: "center", gap: 6, marginBottom: 6 } }, [
    h("div", { className: "dsws-grp", style: { margin: 0 } }, [Ic({ n: "compass", size: 12 }), h("span", null, recTitle)]),
    h("span", { style: { flex: 1 } }),
    h("span", { className: "dsws-seg" + (st.skillView === "list" ? " on" : ""), onClick: function() {
      st.skillView = "list";
      emit(st);
    }, style: { fontSize: 11 } }, tr("skill.list")),
    h("span", { className: "dsws-seg" + (st.skillView === "ring" ? " on" : ""), onClick: function() {
      st.skillView = "ring";
      emit(st);
    }, style: { fontSize: 11 } }, tr("skill.ring"))
  ]);
  const detail = h(PixelSkillDetailModal, {
    st,
    onRetry: function() {
      if (typeof pixelRetryDetail === "function") pixelRetryDetail(st);
    }
  });
  if (st.skillView === "ring") {
    return h("div", { className: "pixel-tab" }, [head, h(RingSkills, { st, rec, list: SKILLS }), detail]);
  }
  return h("div", { className: "pixel-tab" }, [
    head,
    h("div", { style: { marginBottom: 8 } }, rec.map(function(r, i) {
      return h("span", { key: i, className: "dsws-chip dsws-chip-m" }, "/" + r);
    })),
    h(PixelSkillList, {
      items,
      onDetail: function(name) {
        if (typeof pixelOpenDetail === "function") pixelOpenDetail(st, name, itemOf(name));
      },
      onLoad: function(name) {
        inject(st, "/" + name);
      },
      loadingName
    }),
    detail
  ]);
};
