// AUTO-GENERATED by node update-core/build.mjs — DO NOT EDIT. Source: update-core/src/commands.ts
const PACKAGE_NAME = "dsh-mattpocock-skills-deck";
const NPM_REGISTRY = "https://registry.npmjs.org/";
function validVersion(v) {
  return typeof v === "string" && /^\d+\.\d+\.\d+$/.test(v);
}
function parseTriple(v) {
  const parts = String(v).split(".");
  if (parts.length > 3) return null;
  const nums = [];
  for (const p of parts) {
    if (!/^\d+$/.test(p)) return null;
    const n = Number(p);
    if (!Number.isSafeInteger(n)) return null;
    nums.push(n);
  }
  while (nums.length < 3) nums.push(0);
  return [nums[0], nums[1], nums[2]];
}
function compareVersions(a, b) {
  const pa = parseTriple(a);
  const pb = parseTriple(b);
  if (!pa || !pb) throw new Error("invalid-release");
  for (let i = 0; i < 3; i++) {
    if (pa[i] < pb[i]) return -1;
    if (pa[i] > pb[i]) return 1;
  }
  return 0;
}
function buttonCommand(profileName, version) {
  if (typeof profileName !== "string" || !profileName.trim() || !validVersion(version)) return null;
  const name = profileName.trim();
  if (name.length > 255 || name.startsWith("-") || [".", "..", "node_modules"].includes(name)) return null;
  const arg = /^[A-Za-z0-9_.-]+$/.test(name) ? name : JSON.stringify(name);
  return `dsh plugin --profile ${arg} add ${PACKAGE_NAME}@${version} --registry=${NPM_REGISTRY}`;
}
function manualCommand(input) {
  if (input.sourceInstall || input.blockedReason === "source-install" || input.blockedReason === "unknown-profile") return null;
  const name = typeof input.profileName === "string" ? input.profileName.trim() : "";
  if (!name || name.length > 255 || name.startsWith("-") || [".", "..", "node_modules"].includes(name)) return null;
  const arg = /^[A-Za-z0-9_.-]+$/.test(name) ? name : JSON.stringify(name);
  const picks = [input.latestVersion, input.jobTargetVersion, input.installedVersion].filter(validVersion);
  let version = picks.length > 0 ? picks[0] : "latest";
  try {
    const ranked = picks.filter((v) => compareVersions(v, input.runningVersion) >= 0);
    if (ranked.length > 0) {
      version = ranked[0];
      for (const v of ranked) if (compareVersions(v, version) === 1) version = v;
    }
  } catch {
  }
  return `dsh plugin --profile ${arg} add ${PACKAGE_NAME}@${version}`;
}
export {
  buttonCommand,
  manualCommand
};
