// AUTO-GENERATED by node update-core/build.mjs — DO NOT EDIT. Source: update-core/src/service.ts
const PACKAGE_NAME = "dsh-mattpocock-skills-deck";
const NPM_REGISTRY = "https://registry.npmjs.org/";
const CHECK_TIMEOUT_MS = 1e4;
const CONFIRMATION_TTL_MS = 10 * 6e4;
const RECHECK_WINDOW_MS = 2e3;
const MAX_METADATA_BYTES = 256 * 1024;
const INTEGRITY_PATTERN = "^sha512-[A-Za-z0-9+/]{86}==$";
function updateError(code) {
  return Object.assign(new Error(code), { code });
}
function validVersion(v) {
  return typeof v === "string" && /^\d+\.\d+\.\d+$/.test(v);
}
function parseTriple(v) {
  const parts = String(v).split(".");
  if (parts.length > 3) return null;
  const nums = [];
  for (const p of parts) {
    if (!/^\d+$/.test(p)) return null;
    const n = Number(p);
    if (!Number.isSafeInteger(n)) return null;
    nums.push(n);
  }
  while (nums.length < 3) nums.push(0);
  return [nums[0], nums[1], nums[2]];
}
function compareVersions(a, b) {
  const pa = parseTriple(a);
  const pb = parseTriple(b);
  if (!pa || !pb) throw updateError("invalid-release");
  for (let i = 0; i < 3; i++) {
    if (pa[i] < pb[i]) return -1;
    if (pa[i] > pb[i]) return 1;
  }
  return 0;
}
function compareOne(node, op, target) {
  const order = compareTriple(node, target);
  if (op === "=" || op === "") return order === 0;
  if (op === ">") return order === 1;
  if (op === ">=") return order >= 0;
  if (op === "<") return order === -1;
  if (op === "<=") return order <= 0;
  return true;
}
function compareTriple(a, b) {
  for (let i = 0; i < 3; i++) {
    if (a[i] < b[i]) return -1;
    if (a[i] > b[i]) return 1;
  }
  return 0;
}
function upperBound(t, kind, kept) {
  if (kind === "^") {
    if (kept >= 1) return [t[0] + 1, 0, 0];
    return [0, t[1] + 1, 0];
  }
  if (kept >= 2) return [t[0], t[1] + 1, 0];
  return [t[0] + 1, 0, 0];
}
function satisfiesNodeRange(nodeVersion, range) {
  if (range === void 0 || range === null) return true;
  const text = String(range).trim();
  if (text === "" || text === "*") return true;
  const node = parseTriple(String(nodeVersion).replace(/^v/, ""));
  if (!node) return true;
  if (text.includes("||")) return true;
  const parts = text.split(/\s+/).filter(Boolean);
  if (parts.length === 0) return true;
  for (const part of parts) {
    const m = part.match(/^(\^|~|>=|<=|>|<|=)?(.+)$/);
    if (!m) return true;
    const op = m[1] || "";
    const target = parseTriple(m[2]);
    if (!target) return true;
    if (op === "^" || op === "~") {
      const kept = m[2].split(".").length;
      if (compareTriple(node, target) < 0) return false;
      if (compareTriple(node, upperBound(target, op, kept)) >= 0) return false;
      continue;
    }
    if (!compareOne(node, op, target)) return false;
  }
  return true;
}
function byteLength(text) {
  try {
    return new TextEncoder().encode(text).length;
  } catch {
    return text.length;
  }
}
function timeoutSignal(ms) {
  try {
    const ctor = globalThis.AbortSignal;
    if (ctor && typeof ctor.timeout === "function") return ctor.timeout(ms);
  } catch {
  }
  return void 0;
}
async function fetchNpmRelease(fetchImpl, timeoutMs = CHECK_TIMEOUT_MS) {
  let response = null;
  try {
    response = await fetchImpl(`${NPM_REGISTRY}${encodeURIComponent(PACKAGE_NAME)}/latest`, {
      headers: { accept: "application/json" },
      redirect: "error",
      signal: timeoutSignal(timeoutMs)
    });
  } catch {
    throw updateError("check-failed");
  }
  try {
    if (!response.ok) throw updateError("check-failed");
    const declared = Number(response.headers.get("content-length"));
    if (Number.isFinite(declared) && declared > MAX_METADATA_BYTES) throw updateError("invalid-release");
    const text = await response.text();
    if (byteLength(text) > MAX_METADATA_BYTES) throw updateError("invalid-release");
    const value = JSON.parse(text);
    if (value.name !== PACKAGE_NAME || !validVersion(value.version)) throw updateError("invalid-release");
    const version = value.version;
    const nodeRange = value.engines?.node;
    if (nodeRange !== void 0 && typeof nodeRange !== "string") throw updateError("invalid-release");
    const tarballText = value.dist?.tarball;
    const integrity = value.dist?.integrity;
    let tarball;
    try {
      tarball = new URL(String(tarballText));
    } catch {
      throw updateError("invalid-release");
    }
    const registryOrigin = new URL(NPM_REGISTRY).origin;
    const shapeOk = tarball.origin === registryOrigin && !tarball.username && !tarball.password && !tarball.search && !tarball.hash && tarball.pathname === `/${PACKAGE_NAME}/-/${PACKAGE_NAME}-${version}.tgz` && typeof integrity === "string" && new RegExp(INTEGRITY_PATTERN).test(integrity);
    if (!shapeOk) throw updateError("invalid-release");
    return { version, nodeRange: typeof nodeRange === "string" ? nodeRange : "*", integrity, tarball: tarball.href };
  } catch (error) {
    if (error?.code === "check-failed") throw error;
    if (error?.code === "invalid-release") throw error;
    if (response !== null && response.ok) throw updateError("invalid-release");
    throw updateError("check-failed");
  }
}
function createUpdateCore(ports) {
  const checkTimeoutMs = ports.checkTimeoutMs ?? CHECK_TIMEOUT_MS;
  const confirmationTtlMs = ports.confirmationTtlMs ?? CONFIRMATION_TTL_MS;
  let checked = null;
  let checking = null;
  let lastCheckAt = -Infinity;
  function buildSnapshot(env) {
    const blockedReason = env.blockedReason ?? checked?.blockedReason ?? null;
    const fresh = checked !== null && checked.checkId !== null && ports.now() < checked.expiresAt;
    const runningVersion = ports.readRunningVersion();
    const canInstall = Boolean(
      env.eligible && !blockedReason && fresh && checked?.installationKey === env.installationKey && validVersion(runningVersion) && checked?.release && compareVersions(checked.release.version, runningVersion) === 1
    );
    return {
      runningVersion,
      installedVersion: env.installedVersion ?? null,
      latestVersion: checked?.release.version ?? null,
      canInstall,
      blockedReason,
      job: null
    };
  }
  async function status() {
    const env = await ports.readInstalled();
    return buildSnapshot(env);
  }
  async function check() {
    if (checking) return checking;
    if (checked?.checkId && ports.now() - lastCheckAt < RECHECK_WINDOW_MS) {
      const env = await ports.readInstalled();
      const snapshot = buildSnapshot(env);
      return { snapshot, receipt: snapshot.canInstall ? toReceipt() : null };
    }
    lastCheckAt = ports.now();
    checking = (async () => {
      try {
        const env = await ports.readInstalled();
        const release = await fetchNpmRelease(ports.fetchImpl, checkTimeoutMs);
        checked = {
          release,
          checkId: ports.randomId(),
          checkedAt: ports.now(),
          expiresAt: ports.now() + confirmationTtlMs,
          installationKey: env.installationKey,
          blockedReason: satisfiesNodeRange(ports.nodeVersion, release.nodeRange) ? null : "incompatible-node"
        };
        const snapshot = buildSnapshot(env);
        return { snapshot, receipt: snapshot.canInstall ? toReceipt() : null };
      } catch (error) {
        if (checked) checked = { ...checked, checkId: null, expiresAt: 0 };
        throw error;
      } finally {
        checking = null;
      }
    })();
    return checking;
  }
  function toReceipt() {
    if (!checked?.checkId) return null;
    return { checkId: checked.checkId, checkedAt: checked.checkedAt, expiresAt: checked.expiresAt };
  }
  async function install() {
    throw updateError("unsupported");
  }
  return { status, check, install };
}
export {
  CHECK_TIMEOUT_MS,
  CONFIRMATION_TTL_MS,
  INTEGRITY_PATTERN,
  MAX_METADATA_BYTES,
  NPM_REGISTRY,
  PACKAGE_NAME,
  RECHECK_WINDOW_MS,
  compareVersions,
  createUpdateCore,
  fetchNpmRelease,
  satisfiesNodeRange,
  updateError,
  validVersion
};
