// AUTO-GENERATED by node version-control-core/build.mjs — DO NOT EDIT. Source: version-control-core/src/write-ticket.ts
export const TICKET_TTL_MS = 12e4;
export function indexRecordCount(lsFilesText) {
  const parts = String(lsFilesText === void 0 || lsFilesText === null ? "" : lsFilesText).split("\0");
  let n = 0;
  for (const p of parts) if (p !== "") n += 1;
  return n;
}
export function fingerprintInputOf(lsFilesText) {
  return String(lsFilesText === void 0 || lsFilesText === null ? "" : lsFilesText);
}
export function makeTicket(input) {
  return {
    id: String(input.id || ""),
    op: input.op,
    checkedAtMs: input.nowMs,
    expiresAtMs: input.nowMs + TICKET_TTL_MS,
    headOid: String(input.headOid || ""),
    indexFingerprint: input.indexFingerprint === null || input.indexFingerprint === void 0 ? null : String(input.indexFingerprint),
    indexEntries: typeof input.indexEntries === "number" && isFinite(input.indexEntries) ? input.indexEntries : null,
    target: input.target || null
  };
}
export function ticketVerdict(ticket, nowMs, current) {
  if (!ticket || !ticket.id) return { ok: false, reason: "ticket-missing" };
  if (ticket.op !== current.op) return { ok: false, reason: "ticket-op-mismatch" };
  if (!(nowMs < ticket.expiresAtMs)) return { ok: false, reason: "ticket-expired" };
  if (String(current.headOid || "") !== String(ticket.headOid || "")) return { ok: false, reason: "stale-head" };
  if (ticket.op === "commit") {
    if (current.indexAvailable !== true) return { ok: false, reason: "fingerprint-unavailable" };
    if (String(current.indexFingerprint || "") !== String(ticket.indexFingerprint || "")) return { ok: false, reason: "stale-index" };
  }
  if (ticket.op === "push") {
    const a = ticket.target || { mode: "", remote: "", branch: "", localBranch: "" };
    const b = current.target || { mode: "", remote: "", branch: "", localBranch: "" };
    if (a.mode !== b.mode || a.remote !== b.remote || a.branch !== b.branch || a.localBranch !== b.localBranch) return { ok: false, reason: "target-changed" };
  }
  return { ok: true };
}
export function hasIntentToAdd(statusPorcelainV2Z) {
  const text = String(statusPorcelainV2Z === void 0 || statusPorcelainV2Z === null ? "" : statusPorcelainV2Z);
  if (text === "") return false;
  for (const rec of text.split("\0")) {
    if (rec === "") continue;
    if (rec[0] !== "1" && rec[0] !== "2") continue;
    const fields = rec.split(" ");
    if (fields.length >= 3 && fields[2] === "N...") return true;
  }
  return false;
}
export const WRITE_TICKET_SOURCE = "version-control-core/src/write-ticket.ts";
