// 派生文件（#564）：由 packages/dsh-log/dist/host.js 原样复制，内容与日志包 0.1.0 一致，人手不改。
// 旧实现（src/host/logStore.js、src/host/logPhones.js）原地只读留存；运行时走本目录经 logFromPackage.js 接线。
// 共存关系：旧文件只读、新文件派生，真搬迁或真删除旧文件另开票。重新生成：node scripts/derive-log-from-package.mjs。
// AUTO-GENERATED by node packages/dsh-log/build.mjs — DO NOT EDIT. Source: packages/dsh-log/src/host.ts
import {
  buildPhoneNames
} from "./config.js";
import { createLogStore } from "./store.js";
import { buildPhoneName, buildPhoneNames as buildPhoneNames2, resolveHostLogConfig } from "./config.js";
import { parseEventListManifest, checkEventFields, checkEventCounts } from "./config.js";
import {
  LOG_DEBOUNCE_MS,
  LOG_DIR_NAME,
  LOG_SWITCH_FILE,
  formatDailyFileName,
  formatLogFileName,
  createLogStore as createLogStore2
} from "./store.js";
function createHostLog(deps, configInput) {
  const store = createLogStore(deps, configInput);
  const phoneNames = buildPhoneNames(store.config.prefix);
  return { store, phoneNames };
}
function registerHostLogPhones(registry, hostLog) {
  const store = hostLog.store;
  const handlers = {
    logBatch: (args) => store.handleLogBatch(args),
    logExport: (args) => store.handleLogExport(args),
    logClear: (args) => store.handleLogClear(args),
    logGetSwitch: () => store.handleLogGetSwitch(),
    logSetSwitch: (args) => store.handleLogSetSwitch(args)
  };
  const actions = ["logBatch", "logExport", "logClear", "logGetSwitch", "logSetSwitch"];
  for (const action of actions) {
    const name = hostLog.phoneNames[action];
    if (registry.has(name)) {
      throw new Error("[dsh-log] \u7535\u8BDD\u540D\u5DF2\u88AB\u6CE8\u518C\uFF0C\u4E0D\u8986\u76D6\u65E7\u7684\uFF1A" + name);
    }
    registry.set(name, handlers[action]);
  }
  return hostLog.phoneNames;
}
export {
  LOG_DEBOUNCE_MS,
  LOG_DIR_NAME,
  LOG_SWITCH_FILE,
  buildPhoneName,
  buildPhoneNames2 as buildPhoneNames,
  checkEventCounts,
  checkEventFields,
  createHostLog,
  createLogStore2 as createLogStore,
  formatDailyFileName,
  formatLogFileName,
  parseEventListManifest,
  registerHostLogPhones,
  resolveHostLogConfig
};
