// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/cards/PixelCardPin.ts
export const PixelCardPin = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  if (p.kind === "tape") return h("span", { className: "cd-tape", "aria-hidden": true });
  if (p.kind === "sealtop") return h("span", { className: "cd-sealtop", "aria-hidden": true });
  if (p.kind === "big") return h("span", { className: "cd-pin big", "aria-hidden": true });
  return h("span", { className: "cd-pin", "aria-hidden": true });
};
