// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/cards/PixelBlockedChrome.ts
export const PixelBlockedSeal = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  return h("div", { className: "cd-bseal" }, tr("card.blockedSeal", { n: "#" + (p.no || "") }));
};
export const PixelBlockerChip = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  return h("span", { className: "cd-bchip" }, [
    h("b", { key: "b" }, tr("card.blockerIs")),
    h("i", { key: "i" }, "#" + (p.no || "") + " " + (p.title || ""))
  ]);
};
export const PixelDimVeil = function() {
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  return h("div", { className: "cd-dimveil" }, tr("card.blockedDim"));
};
