// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/cards/PixelCardHead.ts
export const PixelCardHead = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  return h("div", { className: "cd-hd" }, [
    p.no || null,
    p.sign ? h(PixelInlineSign, { key: "s", kind: p.sign }) : null,
    p.closed ? h(PixelClosedSeal, { key: "c" }) : null
  ]);
};
