// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/cards/PixelCardTags.ts
export const PixelCardTags = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const tags = p.tags || [];
  return h("div", { className: "cd-lbrow" }, tags.map(function(t, i) {
    const c = String(t.color || "8b5cf6").replace(/^#/, "");
    return h("span", { key: String(i), className: "cd-chip", style: { background: "#" + c, color: cardInkOn(c) } }, t.text);
  }));
};
