// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/cards/PixelIssueCard.ts
export const PixelIssueCard = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const st = CARD_ACTION_STYLE[p.action || "execute"] || CARD_ACTION_STYLE.execute;
  const mainColor = cardColorOf(st.colorKey, p.colorOf || null);
  const blocked = !!(p.blockedBy && p.blockedBy.no);
  const ini = p.lit === void 0 ? false : !!p.lit;
  const pair = React.useState(ini);
  const lit = p.lit !== void 0 ? !!p.lit : pair[0];
  const setLit = pair[1];
  const flip = function(v) {
    if (p.lit === void 0) setLit(v);
    if (p.onLitChange) p.onLitChange(v);
    try {
      const doc = typeof document !== "undefined" ? document : null;
      const o = doc && p.linkedId ? doc.getElementById(p.linkedId) : null;
      if (o && o.classList) {
        if (v) o.classList.add("lit");
        else o.classList.remove("lit");
      }
    } catch (err) {
      void err;
    }
  };
  const cls = "cd-card" + (p.closed ? " old closed" : "") + (blocked && !lit ? " dim" : "") + (lit ? " lit" : "");
  const corner = p.bugCorner ? "bug" : p.closed ? null : p.pickCorner === "ready" ? "ready" : p.pickCorner === "doing" ? "doing" : null;
  const setLitNow = function(e, v) {
    try {
      const el = e && e.currentTarget ? e.currentTarget : null;
      if (el && el.classList) {
        if (v) el.classList.add("lit");
        else el.classList.remove("lit");
      }
    } catch (err) {
      void err;
    }
  };
  const kids = [];
  kids.push(h(PixelCardPin, { key: "pin", kind: p.closed ? "tape" : void 0 }));
  if (corner) kids.push(h(PixelCornerMark, { key: "cor", kind: corner }));
  const headNo = h(PixelCardNo, { key: "no", text: p.noText, action: p.action, colorOf: p.colorOf || null });
  kids.push(h("div", { key: "hd", className: "cd-hd" }, [headNo, p.closed ? h(PixelClosedSeal, { key: "c" }) : null]));
  if (blocked && p.blockedBy) kids.push(h(PixelBlockerBox, { key: "bb", no: p.blockedBy.no, title: p.blockedBy.title }));
  if (blocked && p.blockedBy) kids.push(h(PixelBlockedSeal, { key: "bs", no: p.blockedBy.no }));
  const suffix = p.claimedBy ? h("span", { className: "cd-take" }, tr("card.claimedBy", { n: p.claimedBy })) : null;
  kids.push(h(PixelCardTitle, { key: "tt", text: p.title, suffix }));
  kids.push(h(PixelCardTags, { key: "tg", tags: p.tags || [] }));
  if (p.note) kids.push(h(PixelCardNote, { key: "nt", text: p.note }));
  kids.push(h(PixelCardBtns, { key: "ab", mainLabel: tr("card.act." + (p.action || "execute")), icon: st.icon, mainColor, onMain: p.onMain || null, onNew: p.onNew || null, onCopy: p.onCopy || null, onOpen: p.onOpen || null }));
  kids.push(h(PixelCardFoot, { key: "ft", left: tr("card.updated", { n: p.updatedText || "" }), right: p.footActionText || "" }));
  if (blocked) kids.push(h(PixelDimVeil, { key: "veil" }));
  if (p.linkedId || blocked) kids.push(h(PixelBlockerChip, { key: "chip", no: p.blockedBy && p.blockedBy.no || "", title: p.blockedBy && p.blockedBy.title || "" }));
  const attrs = { className: cls, style: { "--cd-act": "#" + mainColor } };
  if (p.cardId) attrs.id = p.cardId;
  if (p.linkedId) attrs["data-link"] = p.linkedId;
  if (blocked || p.linkedId) {
    attrs.tabIndex = 0;
    attrs.onClick = function(e) {
      setLitNow(e, true);
      flip(true);
    };
    attrs.onFocus = function(e) {
      if (e && e.target === e.currentTarget) {
        setLitNow(e, true);
        flip(true);
      }
    };
    attrs.onBlur = function(e) {
      setLitNow(e, false);
      try {
        if (e && e.currentTarget && e.relatedTarget && e.currentTarget.contains(e.relatedTarget)) return;
      } catch (err) {
        void err;
      }
      flip(false);
    };
  }
  return h("div", attrs, kids);
};
export const PixelBlockerTicket = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const setLitNow = function(e, v) {
    try {
      const el = e && e.currentTarget ? e.currentTarget : null;
      if (el && el.classList) {
        if (v) el.classList.add("lit");
        else el.classList.remove("lit");
      }
    } catch (err) {
      void err;
    }
  };
  const kids = [];
  kids.push(h(PixelCardPin, { key: "pin" }));
  kids.push(h("div", { key: "hd", className: "cd-hd" }, h(PixelCardNo, { text: p.noText, action: "execute", colorOf: p.colorOf || null })));
  kids.push(h(PixelCardTitle, { key: "tt", text: p.title }));
  if (p.tags) kids.push(h(PixelCardTags, { key: "tg", tags: p.tags }));
  if (p.full) kids.push(h(PixelCardBtns, { key: "ab", mainLabel: tr("card.act.execute"), icon: "play", mainColor: cardColorOf("wayfinder:task", p.colorOf || null) }));
  kids.push(h(PixelCardFoot, { key: "ft", left: tr("card.updated", { n: p.updatedText || "" }), right: p.footActionText || "" }));
  kids.push(h(PixelBlockerChip, { key: "chip", no: p.chipNo || p.noText, title: p.chipTitle || p.title }));
  const cls = "cd-card" + (p.lit ? " lit" : "");
  const attrs = { className: cls, style: { "--cd-act": "#a3231a" } };
  if (p.cardId) attrs.id = p.cardId;
  return h("div", attrs, kids);
};
