// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/cards/PixelCardTitle.ts
export const PixelCardTitle = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  return h("h3", { className: "cd-tt" + (p.tall ? " tall" : "") }, [p.text, p.suffix || null]);
};
