// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/cards/PixelCardNo.ts
export const PixelCardNo = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const st = CARD_ACTION_STYLE[p.action || "execute"] || { colorKey: "wayfinder:task", hollow: false };
  const c = cardColorOf(st.colorKey, p.colorOf || null);
  const hollow = p.hollow !== void 0 ? p.hollow : st.hollow;
  const style = hollow ? { borderColor: "#" + c } : { background: "#" + c, color: cardInkOn(c) };
  return h("span", { className: "cd-nonum" + (hollow ? " line" : ""), style }, p.text);
};
