// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/cards/PixelIssueMapCard.ts
export const PixelIssueMapCard = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const blocked = !!(p.blockedBy && p.blockedBy.no);
  const ini = p.lit === void 0 ? false : !!p.lit;
  const pair = React.useState(ini);
  const lit = p.lit !== void 0 ? !!p.lit : pair[0];
  const flip = function(v) {
    if (p.lit === void 0) pair[1](v);
    if (p.onLitChange) p.onLitChange(v);
    try {
      const doc = typeof document !== "undefined" ? document : null;
      const o = doc && p.linkedId ? doc.getElementById(p.linkedId) : null;
      if (o && o.classList) {
        if (v) o.classList.add("lit");
        else o.classList.remove("lit");
      }
    } catch (err) {
      void err;
    }
  };
  const selPair = React.useState(false);
  const sel = selPair[0];
  const cls = "cd-card wide" + (p.open ? "" : " old closed") + (blocked && !lit ? " dim" : "") + (lit ? " lit" : "") + (sel ? " on" : "");
  const setLitNow = function(e, v) {
    try {
      const el = e && e.currentTarget ? e.currentTarget : null;
      if (el && el.classList) {
        if (v) el.classList.add("lit");
        else el.classList.remove("lit");
      }
    } catch (err) {
      void err;
    }
  };
  const kids = [];
  kids.push(h(PixelCardPin, { key: "pin", kind: "sealtop" }));
  const noEl = h("span", { key: "no", className: "cd-nonum", style: { background: "#8b5cf6", color: "#fff" } }, "#" + (p.mapNo || ""));
  kids.push(h("div", { key: "hd", className: "cd-hd" }, [noEl, p.sign ? h(PixelInlineSign, { key: "s", kind: p.sign }) : null, p.open ? null : h(PixelClosedSeal, { key: "c" })]));
  const suffix = p.claimedBy ? h("span", { className: "cd-take" }, tr("card.claimedBy", { n: p.claimedBy })) : null;
  kids.push(h(PixelCardTitle, { key: "tt", text: p.title, tall: true, suffix }));
  if (blocked && p.blockedBy) kids.push(h(PixelBlockedSeal, { key: "bs", no: p.blockedBy.no }));
  kids.push(h(PixelMapDots, { key: "dots", cells: p.dots || [] }));
  kids.push(h(PixelMapStats, { key: "st", kids: p.kids || 0, ready: p.ready || 0, blocked: p.blocked || 0 }));
  kids.push(h(PixelCardBtns, { key: "ab", mainLabel: tr("card.execute"), icon: "play", mainColor: "8b5cf6" }));
  kids.push(h(PixelCardFoot, { key: "ft", left: tr("card.updated", { n: p.updatedText || "" }), right: "" }));
  kids.push(h(PixelMapCorner, { key: "mc" }));
  if (blocked) kids.push(h(PixelDimVeil, { key: "veil" }));
  if (blocked && p.blockedBy) kids.push(h(PixelBlockerChip, { key: "chip", no: p.blockedBy.no, title: p.blockedBy.title }));
  const attrs = { className: cls, style: { "--cd-act": "#8b5cf6" } };
  if (p.cardId) attrs.id = p.cardId;
  if (p.linkedId) attrs["data-link"] = p.linkedId;
  if (blocked || p.linkedId) {
    attrs.tabIndex = 0;
    attrs.onClick = function(e) {
      setLitNow(e, true);
      flip(true);
    };
    attrs.onFocus = function(e) {
      if (e && e.target === e.currentTarget) {
        setLitNow(e, true);
        flip(true);
      }
    };
    attrs.onBlur = function(e) {
      setLitNow(e, false);
      try {
        if (e && e.currentTarget && e.relatedTarget && e.currentTarget.contains(e.relatedTarget)) return;
      } catch (err) {
        void err;
      }
      flip(false);
    };
  } else {
    attrs.onClick = function() {
      selPair[1](!sel);
    };
  }
  return h("div", attrs, kids);
};
