// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/cards/PixelCardFoot.ts
export const PixelCardFoot = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  return h("div", { className: "cd-ft" }, [
    h("span", { key: "l" }, p.left),
    h("span", { key: "r" }, p.right)
  ]);
};
