// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/cards/PixelCardNote.ts
export const PixelCardNote = function(props) {
  const p = props || {};
  if (!p.text) return null;
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  return h("div", { className: "cd-note" }, p.text);
};
