// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/cards/PixelMapDots.ts
export const PixelMapDots = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const cells = [];
  (p.cells || []).forEach(function(c, gi) {
    for (let j = 0; j < (c.n || 0); j++) cells.push(h("i", { key: gi + "-" + j, style: { background: c.color } }));
  });
  return h("div", { className: "cd-grid2" }, cells);
};
export const PixelMapStats = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const cell = function(k, label, v) {
    return h("span", { key: k }, [label + " ", h("b", { key: "b" }, String(v || 0))]);
  };
  return h("div", { className: "cd-mstats" }, [
    cell("k", tr("card.sub"), p.kids),
    cell("r", tr("card.pickReady"), p.ready),
    cell("b", tr("card.blockedCount"), p.blocked)
  ]);
};
export const PixelMapCorner = function() {
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  return h("span", { className: "cd-mapcorner" }, h("b", null, tr("card.map")));
};
