// AUTO-GENERATED by node scripts/build.mjs (px-ts) — DO NOT EDIT. Source: views/skills/PxDoc.ts
const pxDocHeadings = function(md) {
  const out = [];
  String(md == null ? "" : md).split(/\r?\n/).forEach(function(line) {
    const m = /^(#{1,3})\s+(.+)$/.exec(line.trim());
    if (m) out.push({ level: m[1].length, text: m[2].replace(/(\*\*|\*|~~|`)/g, "").replace(/\[([^\]]+)\]\([^)]+\)/g, "$1") });
  });
  return out;
};
const PxDoc = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const st = p.st || null;
  let k = 0;
  const key = function() {
    k += 1;
    return "pxd" + k;
  };
  const openImg = function(src, alt) {
    if (!st || !src) return;
    st.pxImgOverlay = { src, alt: String(alt || "").slice(0, 200) };
    try {
      if (typeof emit === "function") emit(st);
    } catch (e) {
    }
  };
  const pxInline = function(text, inLink) {
    const out = [];
    const pushMarks = function(seg) {
      seg.split(/(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`|~~[^~]+~~)/g).forEach(function(part) {
        if (!part) return;
        let m2 = /^\*\*([^*]+)\*\*$/.exec(part);
        if (m2) {
          out.push(h("strong", { key: key() }, m2[1]));
          return;
        }
        m2 = /^\*([^*]+)\*$/.exec(part);
        if (m2) {
          out.push(h("em", { key: key() }, m2[1]));
          return;
        }
        m2 = /^`([^`]+)`$/.exec(part);
        if (m2) {
          out.push(h("code", { key: key() }, m2[1]));
          return;
        }
        m2 = /^~~([^~]+)~~$/.exec(part);
        if (m2) {
          out.push(h("span", { key: key(), style: { textDecoration: "line-through" } }, m2[1]));
          return;
        }
        out.push(part);
      });
    };
    const pushLinks = function(seg) {
      const re2 = /\[([^\]]+)\]\(([^\s)]+)\)/g;
      let last2 = 0;
      let m2 = null;
      let hit2 = false;
      while ((m2 = re2.exec(seg)) !== null) {
        hit2 = true;
        if (m2.index > last2) pushMarks(seg.slice(last2, m2.index));
        if (/^https?:/i.test(m2[2])) {
          out.push(h("a", { key: key(), href: m2[2], target: "_blank", rel: "noreferrer" }, m2[1]));
        } else {
          out.push(m2[1]);
        }
        last2 = m2.index + m2[0].length;
      }
      if (!hit2) {
        pushMarks(seg);
        return;
      }
      if (last2 < seg.length) pushMarks(seg.slice(last2));
    };
    const re = /!\[([^\]]*)\]\(\s*([^\s)]+)(?:\s+["']([^{"']*)["'])?\s*\)/g;
    let last = 0;
    let m = null;
    let hit = false;
    while ((m = re.exec(text)) !== null) {
      hit = true;
      if (m.index > last) pushLinks(text.slice(last, m.index));
      if (/^https:/i.test(m[2])) {
        const src = m[2];
        const alt = m[1] || "Image";
        const clickable = !inLink && !!st;
        const imgProps = { key: key(), src, alt, loading: "lazy" };
        if (clickable) imgProps.onClick = function() {
          openImg(src, alt);
        };
        out.push(h("img", imgProps));
      } else {
        out.push(m[1] || "");
      }
      last = m.index + m[0].length;
    }
    if (!hit) {
      pushLinks(text);
      return out;
    }
    if (last < text.length) pushLinks(text.slice(last));
    return out;
  };
  const matchListLine = function(line) {
    const im = /^( *)/.exec(line);
    const indent = im ? im[1].length : 0;
    const rest = line.slice(indent);
    let m = /^-\s+\[([ xX])\]\s+(.+)$/.exec(rest);
    if (m) return { indent, ordered: false, task: m[1], text: m[2] };
    m = /^(\d+)\.\s+(.+)$/.exec(rest);
    if (m) return { indent, ordered: true, task: null, text: m[2] };
    m = /^(-|\*)\s+(.+)$/.exec(rest);
    if (m) return { indent, ordered: false, task: null, text: m[2] };
    return null;
  };
  const takeList = function(flat, pos, indent) {
    const lists = [];
    let cur = null;
    let i2 = pos;
    while (i2 < flat.length && flat[i2].indent >= indent) {
      const r = flat[i2];
      if (r.indent > indent) {
        if (cur && cur.items.length > 0) {
          const sub = takeList(flat, i2, r.indent);
          cur.items[cur.items.length - 1].kids = sub.lists;
          i2 = sub.next;
        } else {
          i2 += 1;
        }
      } else {
        if (!cur || cur.ordered !== r.ordered) {
          cur = { ordered: r.ordered, items: [] };
          lists.push(cur);
        }
        cur.items.push({ task: r.task, text: r.text, kids: null });
        i2 += 1;
      }
    }
    return { lists, next: i2 };
  };
  const renderListSeq = function(seq) {
    return seq.map(function(lst, li) {
      void li;
      const tag = lst.ordered ? "ol" : "ul";
      return h(tag, { key: key() }, lst.items.map(function(it, ii) {
        const kids = it.kids && it.kids.length ? renderListSeq(it.kids) : null;
        if (it.task !== null) {
          return h("li", { key: ii }, h("label", { className: "px-task" }, [
            h("input", { key: "c", type: "checkbox", checked: it.task === "x" || it.task === "X", disabled: true }),
            h("span", { key: "t" }, pxInline(it.text, false)),
            kids ? h("span", { key: "k" }, kids) : null
          ]));
        }
        return h("li", { key: ii }, [h("span", { key: "t" }, pxInline(it.text, false))].concat(kids || []));
      }));
    });
  };
  const lines = String(p.md == null ? "" : p.md).split(/\r?\n/);
  const nodes = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const trim = line.trim();
    if (trim.indexOf("```") === 0) {
      const codeLines = [];
      i += 1;
      while (i < lines.length && lines[i].trim().indexOf("```") !== 0) {
        codeLines.push(lines[i]);
        i += 1;
      }
      if (i < lines.length) i += 1;
      nodes.push(h("pre", { key: key() }, h("code", null, codeLines.join("\n"))));
      continue;
    }
    const hm = /^(#{1,6})\s+(.+)$/.exec(trim);
    if (hm) {
      const lv = Math.min(hm[1].length, 3);
      nodes.push(h("h" + lv, { key: key() }, pxInline(hm[2], false)));
      i += 1;
      continue;
    }
    if (/^---+$/.test(trim) || /^\*\*\*+$/.test(trim)) {
      nodes.push(h("hr", { key: key() }));
      i += 1;
      continue;
    }
    const q = /^>\s?(.*)$/.exec(trim);
    if (q) {
      nodes.push(h("blockquote", { key: key() }, pxInline(q[1], false)));
      i += 1;
      continue;
    }
    if (matchListLine(line)) {
      const flat = [];
      while (i < lines.length) {
        const r = matchListLine(lines[i]);
        if (!r) break;
        flat.push(r);
        i += 1;
      }
      renderListSeq(takeList(flat, 0, flat[0].indent).lists).forEach(function(n) {
        nodes.push(n);
      });
      continue;
    }
    if (trim === "") {
      i += 1;
      continue;
    }
    nodes.push(h("p", { key: key() }, pxInline(line, false)));
    i += 1;
  }
  const ov = st && st.pxImgOverlay && st.pxImgOverlay.src ? st.pxImgOverlay : null;
  return h("div", null, [
    h("div", { key: "doc", className: "px-doc", "data-lang": p.lang || "en" }, nodes),
    ov ? h("div", {
      key: "ov",
      className: "px-overlay",
      style: { position: "fixed", zIndex: 1e4 },
      onClick: function(e) {
        try {
          if (e.target === e.currentTarget) {
            st.pxImgOverlay = null;
            emit(st);
          }
        } catch (err) {
        }
      }
    }, h("div", { className: "px-modal", style: { maxWidth: "92%" } }, [
      h("div", { key: "t", className: "px-top" }, [
        h("span", { key: "a", style: { flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } }, ov.alt || "Image"),
        h(PxBtn, { key: "x", mini: true, onClick: function() {
          st.pxImgOverlay = null;
          try {
            emit(st);
          } catch (err) {
          }
        } }, "\u2715")
      ]),
      h("div", { key: "b", className: "px-body", style: { display: "flex", alignItems: "center", justifyContent: "center" } }, h("img", { src: ov.src, alt: ov.alt || "Image", style: { maxHeight: "60vh" } })),
      h("div", { key: "f", className: "px-bot" }, [
        h("span", { key: "u", style: { flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: 11 } }, ov.src),
        h("a", { key: "o", href: ov.src, target: "_blank", rel: "noreferrer", style: { color: "#5b3df0", fontSize: 11, flex: "none" } }, tr("sd.openLink"))
      ])
    ])) : null
  ]);
};
export {
  PxDoc,
  pxDocHeadings
};
