/**
 * views/skills/pxSkillStyles.js — 技能详情像素风皮肤（887 原型 verdict 落地）。
 *
 * 契约：本文件是一段 CSS 文本（ESM 导出）；scripts/build.mjs 去掉行首 export 后拼进
 * src/client/index.js 的拼接标记处，与 kernel/styles.js、vcStyles.js 同一套做法（一源两物）。
 * 注入仍走同一个 styles.insert 接缝（index.js 里紧接着再 insert 一次），没有第二个 <style>。
 * 类名前缀一律 px-，只被本目录的组件引用，不外溢；令牌 --px-* 挂 :root。
 * 固定一套配色（原型定版那套纸面深框），跟随宿主主题换肤是 888 的活，本票不定。
 */
export const PX_STYLE_TEXT = [
  ":root{--px-frame:#3a2c14;--px-paper:#f2e4c0;--px-card:#fffdf4;--px-ink:#2b2113;--px-ink2:#6b5b3e;--px-shadow:#241a0c;--px-gold:#e3a92f;--px-acc:#8b5cf6;--px-ok:#0e8a16;--px-bad:#a3231a;--px-warn:#f59e0b;--px-stripe:#ddcda1;--px-popline:#e8d9ae;--px-hi:#ffe1a1;--px-link:#5b3df0}",
  ".px-btn{font:700 12px ui-monospace,Menlo,Consolas,monospace;border:3px solid var(--px-frame);background:var(--px-paper);color:var(--px-ink);padding:4px 12px;cursor:pointer;box-shadow:2px 2px 0 var(--px-shadow);transition:transform .12s steps(2,end),box-shadow .12s steps(2,end)}",
  ".px-btn:hover{transform:translate(-2px,-2px);box-shadow:4px 4px 0 var(--px-shadow);outline:2px solid var(--px-gold);outline-offset:1px}",
  ".px-btn:active{transform:translate(2px,2px);box-shadow:0 0 0 var(--px-shadow)}",
  ".px-btn:focus-visible{outline:2px dashed var(--px-gold);outline-offset:2px}",
  ".px-btn:disabled{opacity:.6;cursor:wait}",
  ".px-btn.hot{background:var(--px-acc);color:#fff}",
  ".px-btn.mini{padding:1px 8px;font-size:11px}",
  ".px-spin{display:none;width:10px;height:10px;background:var(--px-acc);margin-right:6px;vertical-align:-1px;animation:px-blk .6s steps(2,end) infinite}",
  ".px-btn.loading .px-spin{display:inline-block}",
  "@keyframes px-blk{50%{opacity:.15}}",
  ".px-dot{flex:none;width:10px;height:10px;border:2px solid var(--px-frame)}",
  ".px-num{flex:none;font:700 11px ui-monospace,monospace;background:var(--px-frame);color:var(--px-paper);padding:0 6px;min-width:26px;text-align:center}",
  ".px-ic{display:inline-flex;width:20px;height:20px;align-items:center;justify-content:center;border:2px solid var(--px-frame);font-weight:800;font-size:12px;margin-right:6px;vertical-align:-3px}",
  ".px-ic-ok{background:#d9f2dc;color:var(--px-ok)}.px-ic-err{background:#fbe3e1;color:var(--px-bad)}.px-ic-warn{background:#fdf0d3;color:#9a6a00}.px-ic-idle{background:var(--px-stripe);color:var(--px-ink2)}",
  ".px-seal{position:absolute;left:50%;top:-13px;margin-left:-11px;width:22px;height:22px;background:#c9503f;border:3px solid var(--px-frame)}",
  ".px-skel{height:14px;background:var(--px-stripe);border:2px solid var(--px-frame);margin:8px 0;animation:px-blk 1s steps(2,end) infinite}",
  ".px-banner{background:#fbe3e1;border:3px solid var(--px-frame);border-left:10px solid var(--px-bad);box-shadow:3px 3px 0 var(--px-shadow);padding:8px 10px;font-size:13px;margin:10px 0;display:flex;gap:8px;align-items:center}",
  ".px-banner.warn{background:#fdf0d3;border-left-color:var(--px-warn)}",
  ".px-banner .grow{flex:1}",
  ".px-statusline{font-size:12.5px;background:var(--px-card);border:3px solid var(--px-frame);border-top:8px solid #9a8f78;box-shadow:2px 2px 0 var(--px-shadow);padding:5px 8px;margin:0 0 10px}",
  ".px-toc{background:var(--px-card);border:3px solid var(--px-frame);box-shadow:3px 3px 0 var(--px-shadow);margin:0 0 10px;font-size:12.5px}",
  ".px-toc b{display:block;background:var(--px-frame);color:var(--px-paper);font:700 12px ui-monospace,monospace;letter-spacing:2px;padding:4px 10px}",
  ".px-toc a{display:flex;gap:8px;align-items:center;color:var(--px-ink);text-decoration:none;font-weight:700;padding:6px 10px;cursor:pointer}",
  ".px-toc a+a{border-top:2px solid var(--px-stripe)}",
  ".px-toc a:hover{background:var(--px-frame);color:var(--px-paper)}",
  ".px-toc a:hover .px-num{background:var(--px-paper);color:var(--px-ink)}",
  ".px-doc{line-height:1.85;font-size:13.5px}",
  ".px-doc[data-lang=zh]{line-height:2.05}",
  ".px-doc h1,.px-doc h2,.px-doc h3{font-family:ui-monospace,Menlo,Consolas,Microsoft YaHei,sans-serif}",
  ".px-doc h1{font-size:19px;letter-spacing:1px;border-bottom:4px solid var(--px-frame);padding-bottom:4px}",
  ".px-doc h2{font-size:15px;background:var(--px-popline);border:3px solid var(--px-frame);box-shadow:3px 3px 0 var(--px-shadow);padding:2px 10px;display:inline-block;margin:14px 0 6px}",
  ".px-doc h3{font-size:14px;border-left:8px solid var(--px-gold);padding-left:8px}",
  ".px-doc p{margin:8px 0}",
  ".px-doc ul,.px-doc ol{margin:8px 0;padding-left:0;list-style:none}",
  ".px-doc ul>li{position:relative;padding-left:18px;margin:5px 0}",
  ".px-doc ul>li::before{content:'';position:absolute;left:0;top:.62em;width:8px;height:8px;background:var(--px-acc)}",
  ".px-doc ul ul>li::before{background:var(--px-gold)}",
  ".px-doc ul ul,.px-doc ol ol,.px-doc ul ol,.px-doc ol ul{margin:3px 0}",
  ".px-doc ol{counter-reset:px-it}",
  ".px-doc ol>li{counter-increment:px-it;position:relative;padding-left:38px;margin:7px 0}",
  ".px-doc ol>li::before{content:counter(px-it);position:absolute;left:0;top:2px;font:700 12px ui-monospace,monospace;background:var(--px-frame);color:var(--px-paper);padding:0 6px;border:2px solid var(--px-frame);box-shadow:2px 2px 0 var(--px-shadow)}",
  ".px-doc blockquote{border-left:8px solid var(--px-acc);background:#efe8fb;margin:10px 0;padding:6px 12px}",
  ".px-doc pre{background:#241a0c;color:#f2e4c0;padding:10px 12px;font:12px/1.7 ui-monospace,monospace;overflow:auto;white-space:pre-wrap;border:3px solid var(--px-frame);box-shadow:3px 3px 0 var(--px-shadow)}",
  ".px-doc code{font:700 12px ui-monospace,Menlo,Consolas,monospace;background:var(--px-card);color:var(--px-ink);padding:1px 6px;border:2px solid var(--px-frame);box-shadow:2px 2px 0 var(--px-shadow);white-space:nowrap}",
  ".px-doc pre code{background:none;border:none;box-shadow:none;padding:0;color:inherit;font:inherit;white-space:pre-wrap}",
  ".px-doc a{color:var(--px-link)}",
  ".px-doc em{font-style:normal;font-weight:700;color:var(--px-ink);background:var(--px-hi);padding:0 3px;border-bottom:3px solid var(--px-gold)}",
  ".px-doc hr{border:none;border-top:3px solid var(--px-frame);margin:10px 0}",
  ".px-doc img{max-width:100%;max-height:220px;object-fit:contain;display:block;margin:8px 0;border:3px solid var(--px-frame);background:var(--px-card);cursor:zoom-in}",
  ".px-doc label.px-task{display:flex;gap:8px;align-items:flex-start;margin:5px 0}",
  ".px-skillrow{display:flex;gap:8px;align-items:center;background:var(--px-card);border:3px solid var(--px-frame);box-shadow:3px 3px 0 var(--px-shadow);padding:6px 10px;margin:8px 0;transition:transform .12s steps(2,end),box-shadow .12s steps(2,end)}",
  ".px-skillrow.rec{background:#efe8fb}",
  ".px-skillrow:hover,.px-skillrow:focus-within{transform:translate(-2px,-2px);box-shadow:5px 5px 0 var(--px-shadow);outline:2px solid var(--px-dc,#e3a92f);outline-offset:1px}",
  ".px-sname{font:700 13px ui-monospace,Menlo,Consolas,monospace;min-width:120px}",
  ".px-sname .px-star{color:var(--px-acc)}",
  ".px-suse{flex:1;font-size:12px;color:var(--px-ink2);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
  ".px-overlay{position:absolute;inset:0;background:rgba(28,16,4,.55);display:flex;align-items:center;justify-content:center;z-index:200;padding:14px}",
  ".px-modal{background:var(--px-paper);border:4px solid var(--px-frame);box-shadow:8px 8px 0 var(--px-shadow);width:min(680px,94vw);max-height:86vh;display:flex;flex-direction:column;position:relative}",
  ".px-top{display:flex;align-items:center;gap:8px;padding:8px 12px;border-bottom:3px solid var(--px-frame);font:700 13px ui-monospace,Menlo,Consolas,Microsoft YaHei,sans-serif}",
  ".px-body{padding:12px 16px;overflow:auto;flex:1;min-height:120px}",
  ".px-bot{display:flex;align-items:center;gap:8px;padding:8px 12px;border-top:3px solid var(--px-frame)}",
  ".px-f-ok{animation:px-fok .5s steps(3,end)}",
  ".px-f-err{animation:px-ferr .5s steps(3,end)}",
  "@keyframes px-fok{0%{background:#d9f2dc}100%{background:var(--px-paper)}}",
  "@keyframes px-ferr{0%{background:#fbe3e1}100%{background:var(--px-paper)}}",
  ".px-shake{animation:px-shk .4s steps(4,end)}",
  "@keyframes px-shk{0%,100%{transform:translateX(0)}25%{transform:translateX(-5px)}75%{transform:translateX(5px)}}",
  "@media (prefers-reduced-motion:reduce){.px-btn,.px-skillrow,.px-skel,.px-f-ok,.px-f-err,.px-shake,.px-spin{animation:none!important;transition:none!important}}",
]
