// AUTO-GENERATED by node scripts/build.mjs (px-ts) — DO NOT EDIT. Source: views/skills/PxToc.ts
const PxToc = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const items = p.items || [];
  if (!items.length) return null;
  const rows = items.map(function(label, i) {
    return h("a", {
      key: i,
      onClick: function() {
        if (typeof p.onJump === "function") p.onJump(i);
      }
    }, [
      h(PxNum, { key: "n", n: i + 1 }),
      h("span", { key: "t" }, label)
    ]);
  });
  return h("div", { className: "px-toc" }, [h("b", { key: "h" }, tr("sd.toc"))].concat(rows));
};
export {
  PxToc
};
