// AUTO-GENERATED by node scripts/build.mjs (px-ts) — DO NOT EDIT. Source: views/skills/SkillRow.ts
const SkillRow = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const level = p.level === "warn" ? "warn" : p.level === "bad" ? "bad" : "ok";
  const dc = level === "bad" ? "#a3231a" : level === "warn" ? "#f59e0b" : "#0e8a16";
  return h("div", { className: "px-skillrow" + (p.recommended ? " rec" : ""), style: { "--px-dc": dc } }, [
    h(PxDot, { key: "d", level }),
    h("div", { key: "n", className: "px-sname" }, [
      "/" + p.name,
      p.recommended ? h("span", { key: "s", className: "px-star" }, " \u2605") : null
    ]),
    h("div", { key: "u", className: "px-suse" }, p.use),
    h(PxBtn, {
      key: "b",
      onClick: function() {
        if (typeof p.onDetail === "function") p.onDetail(p.name);
      }
    }, tr("sd.detailBtn"))
  ]);
};
export {
  SkillRow
};
