// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/pixel/PixelBtn.ts
const PixelBtn = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const cls = "pixel-btn" + (p.hot ? " hot" : "") + (p.mini ? " mini" : "") + (p.loading ? " loading" : "");
  return h("button", {
    type: "button",
    className: cls,
    disabled: p.disabled || p.loading || void 0,
    title: p.title || void 0,
    onClick: p.loading ? void 0 : p.onClick
  }, [
    h("span", { key: "spin", className: "pixel-spin", "aria-hidden": true }),
    h("span", { key: "label" }, p.children)
  ]);
};
export {
  PixelBtn
};
