// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/pixel/PixelStateIcon.ts
export const PixelStateIcon = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const mark = p.kind === "ok" ? "✓" : p.kind === "err" ? "✕" : p.kind === "warn" ? "!" : p.kind === "loading" ? "…" : "○";
  return h("span", { className: "pixel-ic pixel-ic-" + (p.kind || "idle"), "aria-hidden": true }, mark);
};
