// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/pixel/PixelBanner.ts
export const PixelBanner = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const warn = p.kind === "warn";
  return h("div", { className: "pixel-banner" + (warn ? " warn" : ""), role: "alert" }, [
    h("b", { key: "mark" }, warn ? "!" : "✕"),
    h("span", { key: "text", className: "grow" }, p.text),
    p.onRetry ? h(PixelBtn, { key: "retry", onClick: p.onRetry }, tr("sd.retry")) : null,
    p.onClose ? h(PixelBtn, { key: "close", onClick: p.onClose }, tr("sd.dismiss")) : null
  ]);
};
