// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/pixel/PixelSeal.ts
export const PixelSeal = function() {
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  return h("span", { className: "pixel-seal", "aria-hidden": true });
};
