// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/pixel/PixelStateIcon.ts
const PixelStateIcon = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const mark = p.kind === "ok" ? "\u2713" : p.kind === "err" ? "\u2715" : p.kind === "warn" ? "!" : p.kind === "loading" ? "\u2026" : "\u25CB";
  return h("span", { className: "pixel-ic pixel-ic-" + (p.kind || "idle"), "aria-hidden": true }, mark);
};
export {
  PixelStateIcon
};
