// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/pixel/PixelSkeleton.ts
const PixelSkeleton = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const widths = ["100%", "82%", "64%"];
  const n = Math.max(1, Math.min(3, Number(p.lines) || 3));
  const bars = [];
  for (let i = 0; i < n; i++) bars.push(h("div", { key: i, className: "pixel-skel", style: { width: widths[i] } }));
  return h("div", { "aria-hidden": true }, bars);
};
export {
  PixelSkeleton
};
