// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/pixel/PixelDot.ts
export const PixelDot = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const bg = p.color || (p.level === "warn" ? "#f59e0b" : p.level === "bad" ? "#a3231a" : p.level === "ok" ? "#0e8a16" : "var(--pixel-dc,#0e8a16)");
  return h("span", { className: "pixel-dot", style: { background: bg }, "aria-hidden": true });
};
