// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/pixel/PixelStatusLine.ts
const PixelStatusLine = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  return h("div", { className: "pixel-statusline" }, [
    h(PixelStateIcon, { key: "ic", kind: p.icon }),
    h("span", { key: "tx" }, p.text)
  ]);
};
export {
  PixelStatusLine
};
