// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/pixel/PixelNum.ts
const PixelNum = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const n = Number(p.n) || 0;
  return h("span", { className: "pixel-num", "aria-hidden": true }, n < 10 ? "0" + n : String(n));
};
export {
  PixelNum
};
