// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/skillDetail/PixelSkillOps.ts
export const pixelDetailCache = {};
let pixelSkelTimer = null;
const pixelClearSkel = function() {
  try {
    if (pixelSkelTimer) {
      clearTimeout(pixelSkelTimer);
      pixelSkelTimer = null;
    }
  } catch (e) {
  }
};
const pixelLangOf = function() {
  try {
    if (typeof promptLang === "function") return promptLang() === "en" ? "en" : "zh";
  } catch (e) {
  }
  return "zh";
};
const PIXEL_STACK_MAX = 3;
const pixelStackOf = function(st) {
  if (!Array.isArray(st.pixelDetailStack)) st.pixelDetailStack = [];
  return st.pixelDetailStack;
};
const pixelSyncTop = function(st) {
  const s = pixelStackOf(st);
  st.pixelDetail = s.length ? s[s.length - 1] : null;
};
const pixelAlive = function(st, created) {
  const s = Array.isArray(st.pixelDetailStack) ? st.pixelDetailStack : [];
  return s.indexOf(created) >= 0;
};
const pixelFail = function(st, created, isMissing) {
  const d = created;
  if (!d || !pixelAlive(st, d)) return;
  pixelClearSkel();
  d.phase = "error";
  d.isMissing = !!isMissing;
  d.phaseText = isMissing ? tr("sd.miss") : tr("sd.fail");
  d.showSkel = false;
  try {
    if (typeof emit === "function") emit(st);
  } catch (e) {
  }
};
const pixelLoad = function(st, created, name) {
  pixelClearSkel();
  pixelSkelTimer = setTimeout(function() {
    const d = created;
    if (!d || !pixelAlive(st, d) || d.phase !== "loading") return;
    d.showSkel = true;
    try {
      if (typeof emit === "function") emit(st);
    } catch (e) {
    }
  }, 2e3);
  const t0 = Date.now();
  let pending = null;
  try {
    pending = typeof host !== "undefined" && host && typeof host.call === "function" ? host.call("skill.readDoc", { name }) : null;
  } catch (e) {
    pending = null;
  }
  if (!pending || typeof pending.then !== "function") {
    pixelFail(st, created, false);
    return;
  }
  pending.then(function(res) {
    try {
      if (res && res.ok === true) log("info", "host.call", { method: "skill.readDoc", latencyMs: Date.now() - t0, ok: true, kind: "skill-doc" });
      else log("warn", "host.call.fail", { method: "skill.readDoc", kind: "skill-doc", errorHash: dswsLogHash(dswsLogTrunc(String("skill-doc-not-ok"), 120, "error")) });
    } catch (eL) {
    }
    const d = created;
    if (!d || !pixelAlive(st, d)) return;
    pixelClearSkel();
    if (res && res.ok === true && res.md) {
      const docPath = String(res && res.path || "");
      const zh = res && res.mdZh ? String(res.mdZh) : "";
      const zhPath = zh ? String(res && res.pathZh || "") : "";
      pixelDetailCache[name] = { md: String(res.md), path: docPath, mdZh: zh || null, pathZh: zhPath || null };
      d.mdEn = String(res.md);
      d.mdZh = zh || null;
      d.pathZh = zhPath || null;
      d.copyText = docPath || null;
      d.docPath = docPath || null;
      d.phase = "ready";
      d.phaseText = tr("sd.ready");
      d.showSkel = false;
      try {
        if (typeof emit === "function") emit(st);
      } catch (e) {
      }
      return;
    }
    pixelFail(st, created, true);
  }, function(e) {
    try {
      log("warn", "host.call.fail", { method: "skill.readDoc", kind: "skill-doc", errorHash: dswsLogHash(dswsLogTrunc(String(e && e.message || e), 120, "error")) });
    } catch (eL) {
    }
    pixelFail(st, created, false);
  });
};
export const pixelOpenDetail = function(st, name, item) {
  if (!st || !name) return;
  const use = item && item.use || "";
  const stack = pixelStackOf(st);
  const top = stack[stack.length - 1];
  if (top && top.name === name && top.phase !== "error") return;
  const created = {
    open: true,
    name,
    titleEn: "/" + name,
    titleZh: "/" + name,
    mdEn: null,
    mdZh: null,
    shortDesc: use,
    // 正文默认英文原文；随包若带中文译文（SKILL.zh.md），弹窗上那颗「中文」按钮就能切过去。
    bodyLang: "en",
    phase: "loading",
    phaseText: tr("sd.fetch"),
    isMissing: false,
    dshLang: pixelLangOf(),
    showSkel: false
  };
  stack.push(created);
  while (stack.length > PIXEL_STACK_MAX) stack.shift();
  pixelSyncTop(st);
  try {
    if (typeof emit === "function") emit(st);
  } catch (e) {
  }
  const cached = pixelDetailCache[name];
  if (cached) {
    created.mdEn = cached.md;
    created.docPath = cached.path;
    created.copyText = cached.path;
    created.mdZh = cached.mdZh;
    created.pathZh = cached.pathZh;
    created.phase = "ready";
    created.phaseText = tr("sd.readyHit");
    try {
      if (typeof emit === "function") emit(st);
    } catch (e) {
    }
    return;
  }
  pixelLoad(st, created, name);
};
export const pixelRetryDetail = function(st) {
  const d = st && st.pixelDetail;
  if (!d || !d.name) return;
  const name = d.name;
  try {
    delete pixelDetailCache[name];
  } catch (e) {
  }
  d.mdEn = null;
  d.mdZh = null;
  d.docPath = null;
  d.pathZh = null;
  d.copyText = null;
  d.copied = false;
  d.phase = "loading";
  d.phaseText = tr("sd.fetch");
  d.isMissing = false;
  d.showSkel = false;
  try {
    if (typeof emit === "function") emit(st);
  } catch (e) {
  }
  pixelLoad(st, d, name);
};
export const pixelCloseDetailAndClean = function(st) {
  pixelClearSkel();
  pixelCloseDetail(st);
};
