// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/skillDetail/PixelSkillDetailModal.ts
export const pixelCloseDetail = function(s) {
  if (!s) return;
  const stack = Array.isArray(s.pixelDetailStack) ? s.pixelDetailStack : [];
  stack.pop();
  s.pixelDetail = stack.length ? stack[stack.length - 1] : null;
  try {
    if (typeof emit === "function") emit(s);
  } catch (e) {
  }
};
export const pixelToggleDetailLang = function(s) {
  const d = s && s.pixelDetail;
  if (!d) return;
  d.bodyLang = d.bodyLang === "zh" ? "en" : "zh";
  try {
    if (typeof emit === "function") emit(s);
  } catch (e) {
  }
};
export const pixelCopyDetailLink = function(s, text) {
  const d = s && s.pixelDetail;
  const done = function() {
    if (!d) return;
    d.copied = true;
    try {
      if (typeof emit === "function") emit(s);
    } catch (e) {
    }
    setTimeout(function() {
      if (!s || s.pixelDetail !== d) return;
      d.copied = false;
      try {
        if (typeof emit === "function") emit(s);
      } catch (e) {
      }
    }, 1500);
  };
  try {
    if (text && typeof navigator !== "undefined" && navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(done, done);
      return;
    }
  } catch (e) {
  }
  done();
};
export const PixelSkillDetailModal = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const s = p.st;
  const d = s && s.pixelDetail;
  const bodyRef = React.useRef(null);
  const fitRef = React.useRef(null);
  const useFit = React.useLayoutEffect || React.useEffect;
  useFit(function() {
    if (!p.full) return void 0;
    const el = fitRef.current;
    if (!el || typeof window === "undefined") return void 0;
    const fit = function() {
      try {
        let host = el.parentElement;
        let limit = 0;
        while (host && host !== document.body) {
          const cs = window.getComputedStyle(host);
          if (/(auto|scroll|hidden)/.test(cs.overflowY) && host.clientHeight >= 200) {
            const pbd = parseFloat(cs.paddingBottom) || 0;
            const r = host.getBoundingClientRect();
            limit = r.top + host.clientTop + host.clientHeight - Math.max(pbd, 8);
            break;
          }
          host = host.parentElement;
        }
        const top = el.getBoundingClientRect().top;
        let h2 = limit ? limit - top : window.innerHeight - top - 12;
        h2 = Math.max(240, Math.min(h2, window.innerHeight - top - 6));
        el.style.height = Math.round(h2) + "px";
        el.style.maxHeight = "none";
      } catch (e) {
      }
    };
    fit();
    window.addEventListener("resize", fit);
    let ro = null;
    try {
      if (typeof ResizeObserver === "function") {
        ro = new ResizeObserver(fit);
        ro.observe(el.parentElement || el);
      }
    } catch (e) {
    }
    return function() {
      window.removeEventListener("resize", fit);
      try {
        if (ro) ro.disconnect();
      } catch (e) {
      }
    };
  }, [p.full, d && d.open, d && d.name]);
  const showStatus = d && d.open && (d.phase === "loading" || d.phase === "error");
  if (!d || !d.open) return null;
  const lang = d.bodyLang === "zh" && d.mdZh ? "zh" : "en";
  const md = lang === "zh" ? d.mdZh : d.mdEn;
  const copyPath = lang === "zh" && d.pathZh ? d.pathZh : d.docPath;
  const title = (lang === "zh" ? d.titleZh : d.titleEn) || d.titleEn || "/" + (d.name || "");
  const heads = pixelDocHeadings(md || "").filter(function(x) {
    return x.level >= 2;
  }).map(function(x) {
    return x.text;
  });
  const canTranslate = !!d.mdZh;
  const toTop = function() {
    try {
      if (bodyRef.current) bodyRef.current.scrollTop = 0;
    } catch (e) {
    }
  };
  const jump = function(i) {
    try {
      const hs = bodyRef.current ? bodyRef.current.querySelectorAll("h2,h3") : [];
      if (hs[i]) bodyRef.current.scrollTop = hs[i].offsetTop - 8;
    } catch (e) {
    }
  };
  const depth = Array.isArray(s.pixelDetailStack) ? s.pixelDetailStack.length : 1;
  const icon = d.phase === "loading" ? "loading" : d.phase === "ready" ? "ok" : d.phase === "error" ? d.isMissing ? "warn" : "err" : "idle";
  const frame = d.phase === "ready" ? "pixel-f-ok" : d.phase === "error" && !d.isMissing ? "pixel-f-err pixel-shake" : "";
  let body = null;
  if (d.phase === "loading" && d.showSkel) body = h(PixelSkeleton, { key: "b", lines: 3 });
  else if (d.phase === "ready") body = h(PixelMarkdown, { key: "b", md, lang, st: s, onSkill: p.onOpenSkill || null, skillNames: p.skillNames || null });
  else if (d.phase === "error" && d.isMissing) {
    body = h("div", { key: "b", className: "pixel-doc", "data-lang": lang }, [
      h("p", { key: "t" }, [h(PixelStateIcon, { key: "i", kind: "warn" }), h("b", { key: "x" }, tr("sd.miss"))]),
      h("p", { key: "m" }, tr("sd.missBody")),
      h("p", { key: "s" }, d.shortDesc || "")
    ]);
  } else if (d.phase === "error") body = h("p", { key: "b" }, tr("sd.noBody"));
  else body = h("p", { key: "b" }, tr("sd.none"));
  const box = h("div", {
    className: "pixel-modal " + frame + (p.full ? " pixel-modal-full" : ""),
    role: "dialog",
    "aria-label": title
  }, [
    h(PixelSeal, { key: "seal" }),
    h("div", { key: "top", className: "pixel-top" }, [
      h("span", { key: "t" }, title),
      depth > 1 ? h("span", { key: "ly", className: "pixel-stack" }, tr("sd.stack", { n: String(depth), m: String(PIXEL_STACK_MAX) })) : null,
      h("span", { key: "f", style: { flex: 1 } }),
      canTranslate ? h(PixelBtn, { key: "l", hot: true, onClick: function() {
        pixelToggleDetailLang(s);
      } }, lang === "en" ? tr("sd.toZh") : tr("sd.toEn")) : null,
      h(PixelBtn, { key: "x", onClick: function() {
        pixelCloseDetail(s);
      } }, tr("sd.close"))
    ]),
    showStatus ? h(PixelStatusLine, {
      key: "st",
      icon,
      texts: d.phase === "loading" ? [tr("sd.fetch"), tr("sd.parse"), tr("sd.layout")] : null,
      text: d.phaseText || tr("sd.idle")
    }) : null,
    h("div", {
      key: "body",
      ref: bodyRef,
      className: "pixel-body"
    }, [
      d.phase === "error" ? h(PixelBanner, {
        key: "bn",
        kind: d.isMissing ? "warn" : "error",
        text: d.phaseText,
        onRetry: !d.isMissing && typeof p.onRetry === "function" ? function() {
          p.onRetry(d.name);
        } : null,
        onClose: function() {
          pixelCloseDetail(s);
        }
      }) : null,
      d.phase === "ready" && heads.length ? h(PixelContents, { key: "toc", items: heads, onJump: jump }) : null,
      body
    ]),
    h("div", { key: "bot", className: "pixel-bot" }, [
      d.copyText ? h(PixelBtn, { key: "c", onClick: function() {
        pixelCopyDetailLink(s, copyPath);
      } }, d.copied ? tr("sd.copied") : copyPath ? tr("sd.copyPath") : tr("sd.copy")) : null,
      !d.isMissing && d.phase === "error" && typeof p.onRetry === "function" ? h(PixelBtn, { key: "r", onClick: function() {
        p.onRetry(d.name);
      } }, tr("sd.retry")) : null,
      h("span", { key: "f", style: { flex: 1 } }),
      h(PixelBtn, { key: "t", mini: true, onClick: toTop }, tr("sd.top"))
    ])
  ]);
  if (p.full) return h("div", { className: "pixel-detail-full", ref: fitRef, "data-fit": "on" }, box);
  return h("div", {
    className: "pixel-overlay",
    onClick: function(e) {
      try {
        if (e.target === e.currentTarget) pixelCloseDetail(s);
      } catch (err) {
      }
    }
  }, box);
};
