// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/skillDetail/PixelSkillOps.ts
export const pixelDetailCache = {};
let pixelSkelTimer = null;
const pixelClearSkel = function() {
  try {
    if (pixelSkelTimer) {
      clearTimeout(pixelSkelTimer);
      pixelSkelTimer = null;
    }
  } catch (e) {
  }
};
const pixelLangOf = function() {
  try {
    if (typeof promptLang === "function") return promptLang() === "en" ? "en" : "zh";
  } catch (e) {
  }
  return "zh";
};
const pixelFail = function(st, name, isMissing) {
  const d = st && st.pixelDetail;
  if (!d || d.name !== name) return;
  pixelClearSkel();
  d.phase = "error";
  d.isMissing = !!isMissing;
  d.phaseText = isMissing ? tr("sd.miss") : tr("sd.fail");
  d.showSkel = false;
  try {
    if (typeof emit === "function") emit(st);
  } catch (e) {
  }
};
export const pixelOpenDetail = function(st, name, item) {
  if (!st || !name) return;
  const use = item && item.use || "";
  st.pixelDetail = {
    open: true,
    name,
    titleEn: "/" + name,
    titleZh: "/" + name,
    mdEn: null,
    mdZh: null,
    shortDesc: use,
    // 正文恒英文：随包原文只有英文一份，中文译文包不在本票范围（888 的另一笔）。
    bodyLang: "en",
    phase: "loading",
    phaseText: tr("sd.fetch"),
    isMissing: false,
    dshLang: pixelLangOf(),
    showSkel: false
  };
  try {
    if (typeof emit === "function") emit(st);
  } catch (e) {
  }
  const created = st.pixelDetail;
  const cached = pixelDetailCache[name];
  if (cached) {
    created.mdEn = cached.md;
    created.docPath = cached.path;
    created.copyText = cached.path;
    created.phase = "ready";
    created.phaseText = tr("sd.readyHit");
    try {
      if (typeof emit === "function") emit(st);
    } catch (e) {
    }
    return;
  }
  pixelClearSkel();
  pixelSkelTimer = setTimeout(function() {
    const d = st.pixelDetail;
    if (!d || d.name !== name || d.phase !== "loading") return;
    d.showSkel = true;
    try {
      if (typeof emit === "function") emit(st);
    } catch (e) {
    }
  }, 2e3);
  const t0 = Date.now();
  let pending = null;
  try {
    pending = typeof host !== "undefined" && host && typeof host.call === "function" ? host.call("skill.readDoc", { name }) : null;
  } catch (e) {
    pending = null;
  }
  if (!pending || typeof pending.then !== "function") {
    pixelFail(st, name, false);
    return;
  }
  pending.then(function(res) {
    try {
      if (res && res.ok === true) log("info", "host.call", { method: "skill.readDoc", latencyMs: Date.now() - t0, ok: true, kind: "skill-doc" });
      else log("warn", "host.call.fail", { method: "skill.readDoc", kind: "skill-doc", errorHash: dswsLogHash(dswsLogTrunc(String("skill-doc-not-ok"), 120, "error")) });
    } catch (eL) {
    }
    const d = st.pixelDetail;
    if (!d || d.name !== name) return;
    pixelClearSkel();
    if (res && res.ok === true && res.md) {
      const docPath = String(res && res.path || "");
      pixelDetailCache[name] = { md: String(res.md), path: docPath };
      d.mdEn = String(res.md);
      d.copyText = docPath || null;
      d.docPath = docPath || null;
      d.phase = "ready";
      d.phaseText = tr("sd.ready");
      d.showSkel = false;
      try {
        if (typeof emit === "function") emit(st);
      } catch (e) {
      }
      return;
    }
    pixelFail(st, name, true);
  }, function(e) {
    try {
      log("warn", "host.call.fail", { method: "skill.readDoc", kind: "skill-doc", errorHash: dswsLogHash(dswsLogTrunc(String(e && e.message || e), 120, "error")) });
    } catch (eL) {
    }
    pixelFail(st, name, false);
  });
};
export const pixelRetryDetail = function(st) {
  const d = st && st.pixelDetail;
  if (!d || !d.name) return;
  const name = d.name;
  const use = d.shortDesc;
  try {
    delete pixelDetailCache[name];
  } catch (e) {
  }
  pixelOpenDetail(st, name, { name, use });
};
export const pixelCloseDetailAndClean = function(st) {
  pixelClearSkel();
  pixelCloseDetail(st);
};
