// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/skillDetail/PixelSkillList.ts
export const PixelSkillList = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const items = p.items || [];
  return h("div", null, [
    h("div", { key: "t", className: "dsws-grp", style: { marginBottom: 6 } }, tr("sd.listTitle")),
    h("div", { key: "rows" }, items.map(function(it) {
      return h(PixelSkillRow, {
        key: it.name,
        name: it.name,
        level: it.level,
        use: it.use,
        recommended: it.recommended,
        onDetail: p.onDetail,
        onLoad: p.onLoad,
        loading: p.loadingName === it.name
      });
    }))
  ]);
};
