// AUTO-GENERATED by node scripts/build.mjs (pixel-ts) — DO NOT EDIT. Source: views/skillDetail/PixelMarkdown.ts
export const pixelDocHeadings = function(md) {
  const out = [];
  String(md == null ? "" : md).split(/\r?\n/).forEach(function(line) {
    const m = /^(#{1,3})\s+(.+)$/.exec(line.trim());
    if (m) out.push({ level: m[1].length, text: m[2].replace(/(\*\*|\*|~~|`)/g, "").replace(/\[([^\]]+)\]\([^)]+\)/g, "$1") });
  });
  return out;
};
export const PixelMarkdown = function(props) {
  const p = props || {};
  const cx = React.useContext(DswsCtx);
  const h = cx ? cx.h : React.createElement;
  const st = p.st || null;
  const skillSet = (function() {
    const names = p.skillNames;
    if (!names || !names.length) return null;
    const s = {};
    for (let i2 = 0; i2 < names.length; i2++) s[String(names[i2])] = true;
    return s;
  })();
  const skillRefOf = function(code) {
    if (!skillSet || typeof p.onSkill !== "function") return null;
    const text = String(code || "").trim();
    const name = text.charAt(0) === "/" ? text.slice(1) : text;
    if (!/^[A-Za-z0-9][A-Za-z0-9_-]*$/.test(name)) return null;
    return skillSet[name] ? name : null;
  };
  let k = 0;
  const key = function() {
    k += 1;
    return "pxd" + k;
  };
  const openImg = function(src, alt) {
    if (!st || !src) return;
    st.pixelImgOverlay = { src, alt: String(alt || "").slice(0, 200) };
    try {
      if (typeof emit === "function") emit(st);
    } catch (e) {
    }
  };
  const pxInline = function(text, inLink) {
    return pxInlineWith(text, inLink, []);
  };
  const pxInlineWith = function(text, inLink, atoms) {
    const mark = function(node) {
      atoms.push(node);
      return "A" + (atoms.length - 1) + "";
    };
    const findClose = function(s, ch, from, need) {
      let i2 = from;
      while (i2 < s.length) {
        if (s[i2] !== ch) {
          i2 += 1;
          continue;
        }
        let run = 1;
        while (i2 + run < s.length && s[i2 + run] === ch) run += 1;
        const fits = need === 1 ? run === 1 : run >= need;
        if (fits) {
          if (ch === "_") {
            const after = i2 + run < s.length ? s[i2 + run] : " ";
            if (/[A-Za-z0-9]/.test(after)) {
              i2 += run;
              continue;
            }
          }
          return i2;
        }
        i2 += run;
      }
      return -1;
    };
    const expand = function(nodes2) {
      const out = [];
      nodes2.forEach(function(n) {
        if (typeof n !== "string") {
          out.push(n);
          return;
        }
        const re = /\u0002A(\d+)\u0002/g;
        let last = 0;
        let m = null;
        while ((m = re.exec(n)) !== null) {
          if (m.index > last) out.push(n.slice(last, m.index));
          const atom = atoms[parseInt(m[1], 10)];
          if (atom !== void 0) out.push(atom);
          last = m.index + m[0].length;
        }
        if (last < n.length) out.push(n.slice(last));
      });
      return out;
    };
    const emphasisOf = function(s) {
      const out = [];
      let i2 = 0;
      while (i2 < s.length) {
        const ch = s[i2];
        if (ch !== "*" && ch !== "_" && ch !== "~") {
          let j = i2;
          while (j < s.length && s[j] !== "*" && s[j] !== "_" && s[j] !== "~") j += 1;
          out.push(s.slice(i2, j));
          i2 = j;
          continue;
        }
        let run = 1;
        while (i2 + run < s.length && s[i2 + run] === ch) run += 1;
        const need = ch === "~" ? 2 : run >= 2 ? 2 : 1;
        if (ch === "~" && run < 2) {
          out.push(s.slice(i2, i2 + run));
          i2 += run;
          continue;
        }
        if (ch === "_") {
          const prev = i2 > 0 ? s[i2 - 1] : " ";
          if (/[A-Za-z0-9]/.test(prev)) {
            out.push(s.slice(i2, i2 + 1));
            i2 += 1;
            continue;
          }
        }
        const openEnd = i2 + need;
        const closeAt = findClose(s, ch, openEnd, need);
        if (closeAt < 0) {
          out.push(s.slice(i2, openEnd));
          i2 = openEnd;
          continue;
        }
        const kids = expand(emphasisOf(s.slice(openEnd, closeAt)));
        if (ch === "~") out.push(h("span", { key: key(), style: { textDecoration: "line-through" } }, kids));
        else if (need === 2) out.push(h("strong", { key: key() }, kids));
        else out.push(h("em", { key: key() }, kids));
        i2 = closeAt + need;
      }
      return out;
    };
    let rest = String(text == null ? "" : text);
    rest = rest.replace(/`([^`]+)`/g, function(all, code) {
      const ref = skillRefOf(code);
      if (ref) {
        return mark(h("code", {
          key: key(),
          className: "pixel-skillref",
          role: "button",
          tabIndex: 0,
          onClick: function() {
            try {
              p.onSkill(ref);
            } catch (e) {
            }
          }
        }, code));
      }
      return mark(h("code", { key: key() }, code));
    });
    rest = rest.replace(/\\([*_`~\[\]()#!>\\\\])/g, function(all, ch) {
      return mark(String(ch));
    });
    rest = rest.replace(/!\[([^\]]*)\]\(\s*([^\s)]+)(?:\s+["']([^"']*)["'])?\s*\)/g, function(all, alt, url) {
      if (!/^https:/i.test(url)) return alt || "";
      const clickable = !inLink && !!st;
      const props2 = { key: key(), src: url, alt: alt || "Image", loading: "lazy" };
      if (clickable) props2.onClick = function() {
        openImg(url, alt);
      };
      return mark(h("img", props2));
    });
    rest = rest.replace(/\[([^\]]+)\]\(([^\s)]+)\)/g, function(all, label, url) {
      if (!/^https?:/i.test(url)) return label;
      return mark(h("a", { key: key(), href: url, target: "_blank", rel: "noreferrer" }, pxInlineWith(label, true, atoms)));
    });
    return expand(emphasisOf(rest));
  };
  const matchListLine = function(line) {
    const im = /^( *)/.exec(line);
    const indent = im ? im[1].length : 0;
    const rest = line.slice(indent);
    let m = /^-\s+\[([ xX])\]\s+(.+)$/.exec(rest);
    if (m) return { indent, ordered: false, task: m[1], text: m[2] };
    m = /^(\d+)\.\s+(.+)$/.exec(rest);
    if (m) return { indent, ordered: true, task: null, text: m[2] };
    m = /^(-|\*)\s+(.+)$/.exec(rest);
    if (m) return { indent, ordered: false, task: null, text: m[2] };
    return null;
  };
  const takeList = function(flat, pos, indent) {
    const lists = [];
    let cur = null;
    let i2 = pos;
    while (i2 < flat.length && flat[i2].indent >= indent) {
      const r = flat[i2];
      if (r.indent > indent) {
        if (cur && cur.items.length > 0) {
          const sub = takeList(flat, i2, r.indent);
          cur.items[cur.items.length - 1].kids = sub.lists;
          i2 = sub.next;
        } else {
          i2 += 1;
        }
      } else {
        if (!cur || cur.ordered !== r.ordered) {
          cur = { ordered: r.ordered, items: [] };
          lists.push(cur);
        }
        cur.items.push({ task: r.task, text: r.text, kids: null });
        i2 += 1;
      }
    }
    return { lists, next: i2 };
  };
  const renderListSeq = function(seq) {
    return seq.map(function(lst, li) {
      void li;
      const tag = lst.ordered ? "ol" : "ul";
      return h(tag, { key: key() }, lst.items.map(function(it, ii) {
        const kids = it.kids && it.kids.length ? renderListSeq(it.kids) : null;
        if (it.task !== null) {
          return h("li", { key: ii }, h("label", { className: "pixel-task" }, [
            h("input", { key: "c", type: "checkbox", checked: it.task === "x" || it.task === "X", disabled: true }),
            h("span", { key: "t" }, pxInline(it.text, false)),
            kids ? h("span", { key: "k" }, kids) : null
          ]));
        }
        return h("li", { key: ii }, [h("span", { key: "t" }, pxInline(it.text, false))].concat(kids || []));
      }));
    });
  };
  const lines = String(p.md == null ? "" : p.md).split(/\r?\n/);
  const nodes = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const trim = line.trim();
    if (trim.indexOf("```") === 0) {
      const codeLines = [];
      i += 1;
      while (i < lines.length && lines[i].trim().indexOf("```") !== 0) {
        codeLines.push(lines[i]);
        i += 1;
      }
      if (i < lines.length) i += 1;
      nodes.push(h("pre", { key: key() }, h("code", null, codeLines.join("\n"))));
      continue;
    }
    const hm = /^(#{1,6})\s+(.+)$/.exec(trim);
    if (hm) {
      const lv = Math.min(hm[1].length, 3);
      nodes.push(h("h" + lv, { key: key() }, pxInline(hm[2], false)));
      i += 1;
      continue;
    }
    if (/^---+$/.test(trim) || /^\*\*\*+$/.test(trim)) {
      nodes.push(h("hr", { key: key() }));
      i += 1;
      continue;
    }
    const q = /^>\s?(.*)$/.exec(trim);
    if (q) {
      nodes.push(h("blockquote", { key: key() }, pxInline(q[1], false)));
      i += 1;
      continue;
    }
    if (matchListLine(line)) {
      const flat = [];
      while (i < lines.length) {
        const r = matchListLine(lines[i]);
        if (!r) break;
        flat.push(r);
        i += 1;
      }
      renderListSeq(takeList(flat, 0, flat[0].indent).lists).forEach(function(n) {
        nodes.push(n);
      });
      continue;
    }
    if (trim === "") {
      i += 1;
      continue;
    }
    nodes.push(h("p", { key: key() }, pxInline(line, false)));
    i += 1;
  }
  const ov = st && st.pixelImgOverlay && st.pixelImgOverlay.src ? st.pixelImgOverlay : null;
  return h("div", null, [
    h("div", { key: "doc", className: "pixel-doc", "data-lang": p.lang || "en" }, nodes),
    ov ? h("div", {
      key: "ov",
      className: "pixel-overlay",
      style: { position: "fixed", zIndex: 1e4 },
      onClick: function(e) {
        try {
          if (e.target === e.currentTarget) {
            st.pixelImgOverlay = null;
            emit(st);
          }
        } catch (err) {
        }
      }
    }, h("div", { className: "pixel-modal", style: { maxWidth: "92%" } }, [
      h("div", { key: "t", className: "pixel-top" }, [
        h("span", { key: "a", style: { flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } }, ov.alt || "Image"),
        h(PixelBtn, { key: "x", mini: true, onClick: function() {
          st.pixelImgOverlay = null;
          try {
            emit(st);
          } catch (err) {
          }
        } }, "✕")
      ]),
      h("div", { key: "b", className: "pixel-body", style: { display: "flex", alignItems: "center", justifyContent: "center" } }, h("img", { src: ov.src, alt: ov.alt || "Image", style: { maxHeight: "60vh" } })),
      h("div", { key: "f", className: "pixel-bot" }, [
        h("span", { key: "u", style: { flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: 11 } }, ov.src),
        h("a", { key: "o", href: ov.src, target: "_blank", rel: "noreferrer", style: { color: "#5b3df0", fontSize: 11, flex: "none" } }, tr("sd.openLink"))
      ])
    ])) : null
  ]);
};
